.test: &test
  variables:
    MAVEN_OPTS: >-
      -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
      -Dorg.slf4j.simpleLogger.showDateTime=true
      -Djava.awt.headless=true
  image: ${CI_JOB_NAME}
  stage: test
  script:
    - 'mvn -B -V -e verify site site:stage'
  except:
    - gh-pages

#maven:3.5-jdk-8-slim: *test

maven:3.6-jdk-8-slim:
  <<: *test
  artifacts:
    paths:
      - target/staging/ono-maven-shared/

pages:
  image: busybox:latest
  stage: deploy
  script:
    - mv target/staging/ono-maven-shared/ public
  dependencies:
    - maven:3.6-jdk-8-slim
  artifacts:
    paths:
    - public
  only:
    - master

