language: java
sudo: false
env:
  - MAVEN_VERSION=3.5.4
  - MAVEN_VERSION=3.6.3
jdk:
  - openjdk8
install:
  - "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}"
  - "./mvnw --show-version --errors --batch-mode -P foss-parent-verification test-compile dependency:go-offline"
script: "./mvnw --show-version --errors --batch-mode -P foss-parent-verification clean verify"
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - mfriedenhagen@gmail.com
